### ISSUE TITLE
Could u pls provide the data preprocessing code?

### ISSUE THREAD

**Issue by abcdvzz** [Zhongdao/gcn_clustering#1]
I am not familiar with this field. So could u pls provide the data preprocessing code? I mean the code for "features+labels+knn_graphs"

**Comment by Zhongdao** [comment]
If you want to use your own data, please extract the features by yourself and save them as the format mentioned in Readme. It is not possible to provide a general preprocessing code since the feature extracting process depends on your own code.

Or you can just use the features provided in this repo, see [here](https://1drv.ms/u/s!Ai0390AjdQNVhUbCRARo8PVc1m3j)
